{% set name = "func-adl" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/func_adl-{{ version }}.tar.gz
  sha256: 7db91c4ea94f009a3a01958e1e732ad276fee585febe5d4943865fbf56654b67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - make-it-sync

test:
  imports:
    - func_adl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iris-hep/func_adl
  summary: Functional Analysis Description Language Base Package
  license: MIT
  license_file: LICENSE
  doc_url: https://gordonwatts.github.io/xaod_usage
  dev_url: https://github.com/iris-hep/func_adl

extra:
  recipe-maintainers:
    - gordonwatts
    - matthewfeickert
